Step2:추가기능및리팩터링
next-step/spring-racingcar pull request #2
Opened 2023-03-22 00:32 UTC by dh-son

리뷰 부탁드립니다.

2023-03-22 23:57 UTC, catsbi requested changes
안녕하세요. 대현님
2단계 추가 기능 및 리팩터링 미션 잘 구현해주셨습니다. 
MVC 패턴에 대해서 이해하고 책임도 적절히 잘 분리해주신 것 같아요. 
몇 가지 피드백을 남겨드렸으니 확인 해주시면 좋을 것 같습니다. 

그리고 추가적으로 현재 몇 가지 일급 객체들이 racingca 패키지와 racingcar.model 패키지에 중복되어 존재하고 그로 인해 컴파일 에러가 발생해서 코드가 실행되지 않는 문제가 있는데 이 부분도 확인해주시기 바랍니다!

피드백 반영 후 다시 리뷰요청 해주세요!

2023-03-22 23:57 UTC, catsbi commented on README.md
> +- [O]: 리팩터링 - 중복코드 제거
체크리스트 👍 
단위별로 체크리스트를 상세히 작성하면 단위테스트 작성하는데 더 편할 수 있습니다 ㅎㅎ

2023-03-22 23:57 UTC, catsbi commented on src/main/java/racingcar/model/Cars.java
> +                .map(it -> new Car(Name.of(it)))
현재 Name이라는 객체가 racingcar.model 패키지에도 있고, racingcar패키지에도 중복되어 존재합니다.  그러다보니 해당 일급 컬렉션(Cars)가 참고하는 Name객체와 자동차 도메인 객체(Car)가 참고하는 Name이 다른 객체를 참조하고 있습니다. 

그래서 컴파일 에러가 발생하고 있는데, 확인해보시면 좋을 것 같습니다.

2023-03-22 23:57 UTC, catsbi commented on src/main/java/racingcar/RacingCarController.java
> +//import static racingcar.Application.racingCarService;
사용하지 않는 코드는 제거해주세요!

2023-03-22 23:57 UTC, catsbi commented on src/main/java/racingcar/RacingCarController.java
> +        racingRequest.validate();
Spring의 Bean Validator라는 개념을 찾아보면 요청객체에 대한 유효성 검증을 좀 더 간결하고 편하게 할 수 있습니다 👍

2023-03-22 23:57 UTC, catsbi commented on src/main/java/racingcar/RacingCarController.java
> +    }
책임도 서비스로 잘 분리되어 MVC 패턴이 적절히 구현되고 REsponseEntity도 잘 사용해주셨네요 👍

2023-03-22 23:57 UTC, catsbi commented on src/main/java/racingcar/RacingCarRepository.java
> +                            rs.getDate("created_at")
id, winner, trial_count같은 매직 리터럴이 중복되서 사용되고 있어요. 휴먼에러의 위험이 있는데 상수로 분리해두면 어떨까요?

2023-03-22 23:57 UTC, catsbi commented on src/main/java/racingcar/RacingCarService.java
> +    }
이처럼 비즈니스 로직에 대해서 전부 Service Layer에서 책임지는 방식을 `트랜잭션 스크립트 패턴` 라고 부릅니다. 
이런 방식은 구현이 편하다는 큰 장점이 있지만,  여러 기능에 대한 책임이 하나의 메서드로 쏠리게 되어 단위테스트를 힘들게하고 OOP패러다임의 SRP 원칙(단일 책임 원칙)을 위반하게 합니다. 이는 곧 중복코드를 유발하고 OCP(오픈 폐쇄 원칙)원칙도 위반하게되어 코드의 변경이 잦아지는데 테스트하긴 힘들어서 문제가 생기기 쉬운 코드가 될 수 있죠 😥

그래서 Service Layer의 메서드는 로직을 직접 다 구현해서 책임지기보단 적절한 도메인에게 요청을 하고 결과를 취합하는 로직 오케스트레이션의 역할만 가지는게 좋습니다. 

예를들어 여기선 racing객체에 레이싱을 반복해서 진행시키는 것도 racing.race() 정도로 메서드 요청만하고, 그 결과만 받도록 하는 방법이 더 권장될 수 있습니다.

2023-03-22 23:57 UTC, catsbi commented on src/main/java/racingcar/model/Name.java
> +public class Name {
일급 객체 👍 

그런데 racingcar 패키지에도 동일한 일급 객체가 있다보니 컴파일 에러가 발생하고 있네요 ㅠ

2023-03-22 23:57 UTC, catsbi commented on src/test/java/racingcar/RacingCarApplicationTests.java
> +		assertThat(playResultDaos.size()).isEqualTo(2);
직접 쿼리를 작성하고, 그 결과를 받아서 검증하는건 프로덕션 코드를 테스트하는게 아니기 때문에, 큰 의미가 없습니다. 
추가적으로 이 테스트는 프로덕션을 통해 실행된 코드가 db에 저장되어있고, 변경이 없다는 가정하에 작성된 테스트로 
격리되지 않은 테스트이기 때문에 깨지기도 쉽고 무엇을 검증하는지에 대한 목표가 명확하지 않습니다. 

테스트 자체로 의미를 가질 수 있게 격리성을 높혀보는건 어떨까요?

2023-03-23 03:32 UTC, dh-son commented on src/main/java/racingcar/RacingCarController.java
> +//import static racingcar.Application.racingCarService;
수정완료했습니다.

2023-03-23 03:34 UTC, dh-son commented on src/main/java/racingcar/model/Cars.java
> +                .map(it -> new Car(Name.of(it)))
racingcar.model 패키지에만 Name 객체가 존재합니다. git merge 과정에서 잘못 올라갔습니다.

2023-03-23 03:45 UTC, dh-son commented on src/main/java/racingcar/RacingCarController.java
> +        racingRequest.validate();
수정완료했습니다.

2023-03-23 03:45 UTC, dh-son commented on src/main/java/racingcar/RacingCarController.java
> +    }
감사합니다.

2023-03-23 03:50 UTC, dh-son commented on src/main/java/racingcar/RacingCarRepository.java
> +                            rs.getDate("created_at")
수정완료했습니다.

2023-03-23 03:51 UTC, dh-son commented on src/main/java/racingcar/model/Name.java
> +public class Name {
git merge 시 잘못 처리 되었습니다. racingcar.model 패키지에만 Name가 존재합니다.

2023-03-23 03:52 UTC, dh-son commented on src/test/java/racingcar/RacingCarApplicationTests.java
> +		assertThat(playResultDaos.size()).isEqualTo(2);
jdbcTemplate을 이용한 쿼리 작업을 처음 해보는 것 이여서 문법 오류가 있는지 확인하려고 작성했습니다.

2023-03-23 03:58 UTC, dh-son commented on src/main/java/racingcar/RacingCarService.java
> +    }
수정완료했습니다.

2023-03-23 04:00 UTC, dh-son commented on README.md
> +- [O]: 리팩터링 - 중복코드 제거
네 알겠습니다. 감사합니다.

2023-03-24 04:54 UTC, catsbi requested changes
대현님 피드백 반영 잘 해주셨습니다 👍 
코드가 한결 가독성도 높아지고 유효성 검증까지 잘 구현된것 같네요 💯 
그런데, 요구사항 중 console application에서 중간 기록을 삭제하고 최종 우승자와 최종우승자의 이동 거리만 출력하도록 바꾸라는 조건이 있었는데 이 부분이 안된 것 같습니다!. 

해당 요구사항 구현 후 다시 리뷰요청 부탁드려요!

2023-03-24 04:54 UTC, catsbi commented on src/main/java/racingcar/RacingCarController.java
> +    public ResponseEntity<RacingResponse> racingGame(@Valid @RequestBody RacingRequest racingRequest) {
Bean Validation을 잘 활용해주셨네요 👍 
@Valid와 @Validated 애노테이션 둘 다 유효성을 검증하는 애노테이션인데, 
@Valid는 자바 표준 검증 애너테이션이고 Validated는 스프링 전용 검증 애노테이션이라는 차이가 있죠. 이를 잘 구분해서 사용하면 좋습니다

2023-03-24 14:18 UTC, dh-son commented on src/main/java/racingcar/RacingCarController.java
> +    public ResponseEntity<RacingResponse> racingGame(@Valid @RequestBody RacingRequest racingRequest) {
좋은 정보 알려주셔서 감사합니다! 개인적으로 두개의 어노테이션 사용법을 정확히 익히도록 할게요.

2023-03-25 11:24 UTC, catsbi approved these changes
대현님 미흡한 요구사항도 잘 구현해 주셨네요. 💯 
이번미션은 여기서 마무리하도록 하겠습니다 고생하셨습니다!

2023-03-25 11:24 UTC, merged