🚀 2단계 - 추가 기능 및 리팩터링
next-step/spring-racingcar pull request #64
Opened 2023-05-01 11:21 UTC by hongmoSung

2단계 리뷰요청 드립니다.

## 요구사항

- [x] 게임 플레이 이력 조회 API 구현
- [x] 기존 기능 수정 - 출력 방석 수정
- [x] 리팩터링 - 중복 코드 제거

2023-05-01 15:27 UTC, qhals321 requested changes
안녕하세요 홍모님!! 코드리뷰 적용이 엄청 빠른데요!! 💯💯💯💯💯

몇 가지 코멘트 남겼습니다!! (추가적으로 관련 키워드와 링크도 추가했습니다!)

그리고 이번 단계에서는 나눠주신 레이어(Controller, Service, Repository)에 대한 홍모님만의 정의를 세워보는 단계가 되었으면 좋겠어요!! 레이어에 대한 정의가 나온다면 이에 맞게 추가적인 코드리뷰 진행하면 좋을 것 같아요!! (레이어에 대한 정의는 각자 다를 수 있으니깐요~!)

회사에서 지금과 같은 레이어를 나눠서 사용하셔서 나눠서 진행하시긴 하셨지만 각 레이어가 어떤 역할인지 홍모님이 고민해주셔서 공유해주신다면(dm 으로도 언제나 환영입니다~.) 같이 의견도 공유하면서 진행되면 좋을 것 같아요!!  🙇🙇🙇🙇 파이팅입니다!! 🔥🔥🔥🔥🔥

2023-05-01 15:27 UTC, qhals321 commented on src/main/java/racingcar/data/HistoryRepository.java
> +    }
매번 반복문으로 `insert` 하는 것보다 [batch insert](https://www.baeldung.com/spring-jdbc-batch-inserts) 기능을 사용해보면 어떨까요?!

일반 insert 를 여러번 하는 것과 batch insert 하는 차이가 무엇일지 고민해보는 것도 좋을 것 같아용!

2023-05-01 15:27 UTC, qhals321 commented on src/test/java/racingcar/business/RacingServiceTest.java
> +@WebMvcTest(RacingService.class)
해당 테스트는 대부분 Mvc (대부분 컨트롤러) 슬라이스 테스트를 할 때 많이 사용돼요!!

서비스를 슬라이스해서 테스트하시는 거라면 [MockitoExtension](https://effortguy.tistory.com/142) 을 이용해서 슬라이스 테스트를 해보시는 건 어떨까요?!
(서비스 레이어를 슬라이스 테스트 할 지 통합 테스트를 할 지는 선호에 따라 많이 다르긴 해요! 이 부분에 대해 각 테스트의 장단점을 한 번 즈음 생각해보시는 것도 좋을 것 같아요!!)

2023-05-01 15:27 UTC, qhals321 commented on src/test/java/racingcar/presentation/RacingCarApiTest.java
>  @SpringBootTest
이 부분에서는 `@WebMvcTest` 를 이용해 컨트롤러 슬라이스 테스트를 만들어 보시는 경험도 좋을 것 같아요!!

MockMvc 활용은 [링크](https://gom20.tistory.com/123)를 보시면 더 편하실 것 같아요!! (api 를 호출하는 형식으로 진행하셔서 각 dto 에 원하는 값이 제대로 매핑되는지 테스트도 가능해져요!!)

2023-05-01 15:27 UTC, qhals321 commented on src/main/java/racingcar/data/HistoryRepository.java
> +    private final SimpleJdbcInsert simpleJdbcInsert;
`SimpleJdbcInsert` 활용!! 너무 좋네용~! 💯💯💯

2023-05-01 15:27 UTC, qhals321 commented on src/main/java/racingcar/presentation/RacingCarApi.java
> +@RequestMapping("/plays")
💯💯💯💯💯💯

2023-05-01 15:27 UTC, qhals321 commented on src/main/java/racingcar/presentation/dto/PlayHistory.java
> +        }
해당 해시코드를 재정의한 이유는 무엇인가요?! 

31이란 숫자는 어떤 의미를 하는 건가용?? 🤔

2023-05-01 15:27 UTC, qhals321 commented on src/main/java/racingcar/data/HistoryRepository.java
> +            parameters.put("created_at", LocalDateTime.now());
타임같은 경우는 위에 변수로 now 를 찍어놓고 모든 값에 생성 시간을 같게 해주면 운영할 때 히스토리 추적이 더 용이해지더라고요!!

2023-05-08 09:03 UTC, qhals321 requested changes
진짜 너무 깔끔하게 수정이 되었네요!! 💯💯💯💯💯

추가적으로 리팩토링이 되었음 하는 부분이 있습니다~!

아래 사진을 보게 되면 Presentation layer -> Business layer -> Persistence layer 가 있는데 콘솔 부분은 아무래도 Presentation layer 에 속할 것 같은데 Business layer(Service) 부분은 Console 이랑 웹이랑 공유할 수 있도록 리팩토링 해보는 건 어떨까요?! 🤔 콘솔이나 웹이나 같은 db 에 저장할 수 있도록이요~.
![image](https://user-images.githubusercontent.com/63535027/236782501-214efe9d-0a75-4ffd-b354-afbf5fddf7eb.png)

만약 스프링 기능을 같이 사용하는 방식을 찾으신다면 힌트로 [CommandLineRunner](https://recordsoflife.tistory.com/385) 로 같이 사용할 수 있을 것 같아요! 다른 방법들도 있겠지만 저는 저 방법을 사용할 것 같네요!! 관련된 부분에서 궁금한 부분이 생기시면 언제든 dm 부탁드려용

2023-05-08 09:03 UTC, qhals321 commented on src/main/java/racingcar/business/RacingService.java
> +                            .collect(Collectors.toList());
여기서 gameResult 만큼 쿼리([n+1](https://incheol-jung.gitbook.io/docs/q-and-a/spring/n+1))가 나갈 것 같은데 어떻게 개선시킬 수 있을까요?!

키워드는 in 쿼리입니다~!

2023-05-09 13:02 UTC, hongmoSung commented on src/main/java/racingcar/business/RacingService.java
> +                            .collect(Collectors.toList());
말씀하신 대로 반복문만큼 쿼리가 나가는 부분을 수정하였습니다.

2023-05-10 10:28 UTC, qhals321 commented on src/test/java/racingcar/presentation/RacingCarApiTest.java
> +                .content("{ \"names\" : null, " +
json 형식 만들기 힘드시면 ObjectMapper 를 직접 가져오셔서 json 으로 바꾸셔도 편하실 거에요~!

2023-05-10 10:30 UTC, qhals321 commented on src/main/java/racingcar/business/domain/RacingCars.java
> +                .collect(Collectors.toList());
',' 기준으로 split 하는 부분을 과연 도메인에 있는 RacingCars 역할인지 한 번 고민해봐도 좋을 것 같아요!

만약에 콘솔과 web 에서 받는 형식이 달라지게 되거나 혹은 화면쪽에서 , 기준이 아니라 : 로 바꾸게 된다면 서비스까지 변경 포인트가 침투당할 것 같아서요! 

이런 부분들은 꽤나 빈번하게 일어나므로 presentation layer 와 business layer 나눌 때 이런 룰들도 고민해보시는 것도 좋을 것 같아요~!

2023-05-10 10:31 UTC, qhals321 approved these changes
안녕하세요 홍모님!!

정말 빠르고 리뷰에 맞게 잘 구현해주셨네요 💯💯💯💯

아래 간단하게 코멘트 남긴 부분도 있으니 확인해주세요~!! (간단한 제 생각입니당!)

다른 부분들은 너무 깔끔하게 잘 구현해주셔서 이만 머지 진행하겠습니다! 이번 미션 수고 정말 많으셨습니다~! 🙇

2023-05-10 10:32 UTC, merged