🚀 2단계 - 추가 기능 및 리팩터링
next-step/spring-racingcar pull request #81
Opened 2023-05-06 03:39 UTC by chuvaaa

안녕하세요.

2단계 과제 작성하여 pr 남깁니다!

감사합니다.

2023-05-07 05:09 UTC, Hyeon9mak requested changes
안녕하세요 민수님, 2단계 진행 고생하셨습니다.
함께 이야기나눠보면 좋을 부분 코멘트 남겼으니 확인해주세요! 🙇‍♂️

2023-05-07 05:09 UTC, Hyeon9mak commented on src/main/java/racingcar/RacingCarConsoleApplication.java
>          int count = scanner.nextInt();
console 게임에서도 간단하게 view 와 domain 영역을 분리해주면 어떨까요?

2023-05-07 05:09 UTC, Hyeon9mak commented on src/main/java/racingcar/RacingCarConsoleApplication.java
> +        RacingCars racingCars = new RacingCars(request.getConvertRequestNameToCarList());
요청과 응답이라는 표현은 사실 http 통신의 request / response 에 조금 더 가까워 보여요.
console application 입장에서 꼭 request 를 만들어줄 필요가 있을까요?

2023-05-07 05:09 UTC, Hyeon9mak commented on src/main/java/racingcar/RacingCarConsoleApplication.java
>  }
intellij 를 사용하시는 경우 `Editor` > `General` > `Ensure every saved file ends with a line break` 를 체크하시면 파일 마지막에 자동으로 개행이 적용됩니다.

![image](https://user-images.githubusercontent.com/37354145/236658274-9ed3dd5e-17d1-4cb2-b944-728270770f0d.png)

2023-05-07 05:09 UTC, Hyeon9mak commented on src/main/java/racingcar/RacingCarConsoleApplication.java
> +import racingcar.service.RacingService;
intellij 에서 사용되지 않는 import 관리, 자동 코드 리포맷팅에는 아래 설정이 편리하더라구요.
`Preferences` > `Tools` > `Actions on Save`

![image](https://user-images.githubusercontent.com/37354145/236658289-9f43eda3-7cff-46fa-8d39-15c019bcec3d.png)

2023-05-07 05:09 UTC, Hyeon9mak commented on src/main/java/racingcar/repository/RacingResultRepository.java
> +    }
`RowMapper<T> rowMapper` 를 필드 멤버로 주입하고, 이를 사용해서 list 조회 결과를 반환하도록 해보면 어떨까요?

2023-05-07 05:09 UTC, Hyeon9mak commented on src/main/java/racingcar/service/RacingService.java
> +        List<PlayResult> playListResult =  racingResultRepository.getResultAll();
사용되지 않는 걸로 보여요 😱

2023-05-07 05:09 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
자동차 경주 데이터가 `", "` 형태로 출력되고, 역정규화되어 저장되지만
비즈니스 로직에서까지 `", "` 에 대한 정보를 인지하고 있을 필요가 있을까요?
만약 `", "` 대신 다른 형태로 표현한다는 요구사항이 생기면, 자동차 경주 로직을 포함하고 있는 `RacingCars` 도 함께 변경되어야 할 것 같아요.

2023-05-07 09:05 UTC, chuvaaa commented on src/main/java/racingcar/RacingCarConsoleApplication.java
> +import racingcar.service.RacingService;
오오 이런게 있었군요!

2023-05-07 23:29 UTC, chuvaaa commented on src/main/java/racingcar/RacingCarConsoleApplication.java
>  }
좋은정보 감사합니다!

2023-05-07 23:33 UTC, chuvaaa commented on src/main/java/racingcar/service/RacingService.java
> +        List<PlayResult> playListResult =  racingResultRepository.getResultAll();
앗 소스 수정 과정에서 남아버렸군요 감사합니다!

2023-05-07 23:36 UTC, chuvaaa commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
그럼 이 부분은 RacingCars 에서 수행하는게 아니고 데이터를 불러오거나 넣어줄때 따로 수행하는게 좋은걸까요?

2023-05-07 23:53 UTC, chuvaaa commented on src/main/java/racingcar/repository/RacingResultRepository.java
> +    }
말씀하신대로 적용해 보았습니다 😄

2023-05-08 00:08 UTC, chuvaaa commented
안녕하세요 ! 
몇몇 부분은 수정 적용하였고, 궁금한거는 코멘트 남겼습니다!
감사합니다!

2023-05-08 07:35 UTC, chuvaaa commented
그리고 과제를 진행하며 DDD를 좀 찾아보다 궁금한게 생겨서 질문 남겨놓습니다!

도메인주도로 설계하여 개발하게 되어 도메인에 비즈니스 로직이 들어가고 도메인이 커지다보면

특정 도메인의 비즈니스 로직에서 다른 도메인이 필요 할 때가 있을거 같은데
그런 경우 도메인의 메소드를 호출 하는 부분에서 인자값 이라거나 도메인 안에서 다른 도메인을 생성하여 사용해도 되는걸까요?

그리고 몇몇 글에서는 도메인 내에서 직접 데이터에 (infra 계층) 접근 하기도 한다는거 같은데 
이 부분은 제가 찾아본게 맞는지 궁금합니다.

2023-05-09 00:01 UTC, Hyeon9mak approved these changes
안녕하세요 민수님, 2단계 피드백 반영 고생하셨습니다.
추가로 고민해보시면 좋을 부분 코멘트 남겼어요!
가볍게 확인해주세요 😄 👍 

> 도메인주도로 설계하여 개발하게 되어 도메인에 비즈니스 로직이 들어가고 도메인이 커지다보면
특정 도메인의 비즈니스 로직에서 다른 도메인이 필요 할 때가 있을거 같은데
그런 경우 도메인의 메소드를 호출 하는 부분에서 인자값 이라거나 도메인 안에서 다른 도메인을 생성하여 사용해도 되는걸까요?

도메인이라는 용어를 정리해보면 좋을 것 같은데요, 도메인이란 한마디로 '소프트웨어로 해결하고자 하는 문제 영역'입니다.
id, getter, setter 등을 가진 객체모델이 아닌 domain 패키지 내부에서 수행되는 모든 비즈니스 로직의 흐름을 뜻한다고 생각해요.
아마도 민수님께서 질문 주신 내용은 비즈니스 로직 수행을 위해 활용되는 `VO` 혹은 `엔티티(식별자 + VO)`인 것 같아요.

도메인주도설계에서 자신 외 다른 도메인이 필요하다는 뜻은 
"내가 해결하고자 하는 문제 외 다른 문제의 도움이 필요하다." 라는 다소 요상한 뜻이 되는데요,
이 경우 이론적으로는 바운디드 컨텍스트를 다시 확인 후 애그리게이션이 진행되어야겠고,
기술적으로는 다른 도메인에서 사용되는 `VO` 혹은 `엔티티(식별자 + VO)` 비슷하고 중복되는 로직이 많지만
엄연히 다르게 사용되는 내 도메인만의 `VO` 혹은 `엔티티(식별자 + VO)`를 만들어서 관리해야한다고 생각합니다.

> 몇몇 글에서는 도메인 내에서 직접 데이터에 (infra 계층) 접근 하기도 한다는거 같은데
이 부분은 제가 찾아본게 맞는지 궁금합니다.

"OO한 방법을 통해 현재 데이터를 영속화한다." 까지가 도메인이라면 그럴 수 있겠으나,
일반적으로 도메인 영역에서 관심사는 "데이터를 영속화한다."에서 끝나지, 어떻게 영속화하는가는 관심사가 아닐거 같아요.
infra 계층에 직접 접근하여 메서드를 호출하는 방식보다는 영속화시킬 방법이 명세되어 있는 인터페이스를 호출하고,
infra 계층에서 도메인 계층의 인터페이스를 구현하여 DIP 를 적용하는 방법이 있겠네요. 🤔 

추가로 궁금하신점 코멘트, DM 남겨주세요.
다음 미션도 화이팅입니다 💪

2023-05-09 00:01 UTC, Hyeon9mak commented on src/main/java/racingcar/repository/RacingResultRepository.java
> +        return jdbcTemplate.query(sql, ROW_MAPPER);
조회 쿼리가 정말 간결해졌네요!! 👍 👍

2023-05-09 00:01 UTC, Hyeon9mak commented on src/main/java/racingcar/repository/rowmapper/PlayResultRowMapper.java
> +    }
```suggestion
    private List<RacingCar> getRacingCarListToJson(String jsonString){
        try {
            jsonString = jsonString.substring(1, jsonString.length()-1);
            return objectMapper.readValue(jsonString, new TypeReference<>() {});
        } catch (JsonProcessingException e) {
            throw new RuntimeException("racingcars json -> List<RacingCar> 변환실패");
        }
    }
```
요렇게 try 내부에 모든 로직을 수행하면 가독성이 조금 더 올라갈 것 같아요 😄 👍

2023-05-09 00:01 UTC, Hyeon9mak commented on src/main/java/racingcar/domain/RacingCars.java
> +    }
!!! 오 민수님 말씀에 설득되었습니다 💯 👍 

저는 웹 자동차 경주에서 참여 자동차 표현 방식에 이미지 등을 사용하는 경우에도
자동차 경주 비즈니스 로직 수정 없이 이미지 관련 코드 추가만으로 확장이 가능하기 위한 관점에서 말씀드린 것이었어요.

미래의 일을 예측할 순 없지만, 앞으로 자동차 경주 게임의 요구사항 변경 포인트가 어떤 부분에 자주 발생할까 고민해볼 때
다른 표현방식으로 확장이 아닌 단순히 `", "` 를 "|"` 등으로 변경하는게 될수도 있겠는데
이럴 때는 민수님께서 말씀해주신 방식이 훨씬 유지보수에 유리하겠네요.

중요한 것은 앞으로 어떤 포인트에서 어떤 변화가 자주 일어날지 예측하고 그게 쉽도록 코드를 작성해두는 것이라고 생각하는데,
민수님께서 예측하신 포인트에는 민수님의 방식이 가장 좋은 것 같습니다! 설득되었습니다! 👍 👍

2023-05-09 00:01 UTC, Hyeon9mak commented on src/main/java/racingcar/RacingCarConsoleApplication.java
>          int count = scanner.nextInt();
앗! 피드백이 누락되었네요 😱

2023-05-09 00:01 UTC, merged